package ui.theme

import androidx.compose.ui.unit.dp

val SUPER_LARGE_PADDING = 40.dp
val EXTRA_LARGE_PADDING = 32.dp
val LARGE_PADDING = 24.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp
val SUPER_SMALL_PADDING = 3.dp

val PAGING_INDICATOR_HEIGHT = 8.dp
val PAGING_INDICATOR_WIDTH = 8.dp
val SELECTED_PAGING_INDICATOR_WIDTH = 16.dp
val PAGING_INDICATOR_SPACING = 4.dp
val BUTTON_HEIGHT = 56.dp
val BUTTON_HORIZONTAL_PADDING = 55.dp

val PET_ITEM_HEIGHT = 260.dp
val PET_ITEM_WIDTH = 200.dp
val PAGER_ITEM_HEIGHT = 410.dp
val HOME_APPOINTMENTS_HEIGHT = 90.dp
val CARD_ELEVATION = 4.dp
val NETWORK_ERROR_ICON_HEIGHT = 120.dp

val INFO_ICON_SIZE = 32.dp

val MIN_SHEET_HEIGHT = 140.dp
val EXPANDED_RADIUS_LEVEL = 0.dp

